default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>

development:
  <<: *default
  database: pharma_site_development

test:
  <<: *default
  database: pharma_site_test

production:
  <<: *default
  database: pharma_site_production
  username: pharma_site
  password: <%= ENV["PHARMA_SITE_DATABASE_PASSWORD"] %>
